### ISSUE TITLE
ImportError: cannot import name parseWsUrl

### ISSUE THREAD

**Issue by hdknr** [hdknr/crosschat#1]
- https://github.com/crossbario/crossbar/issues/709

``` bash

vagrant@ubuntu-14:/vagrant/crosschat/server$ crossbar start
2016-04-17T03:42:05+0000 [Controller   2016] Traceback (most recent call last):
2016-04-17T03:42:05+0000 [Controller   2016]   File "/home/vagrant/.anyenv/envs/pyenv/versions/2.7.10/bin/crossbar", line 9, in <module>
2016-04-17T03:42:05+0000 [Controller   2016]     load_entry_point('crossbar==0.13.0', 'console_scripts', 'crossbar')()
2016-04-17T03:42:05+0000 [Controller   2016]   File "/home/vagrant/.anyenv/envs/pyenv/versions/2.7.10/lib/python2.7/site-packages/crossbar/controller/cli.py", line 992, in run
2016-04-17T03:42:05+0000 [Controller   2016]     options.func(options, reactor=reactor)
2016-04-17T03:42:05+0000 [Controller   2016]   File "/home/vagrant/.anyenv/envs/pyenv/versions/2.7.10/lib/python2.7/site-packages/crossbar/controller/cli.py", line 560, in run_command_start
2016-04-17T03:42:05+0000 [Controller   2016]     from crossbar.controller.node import maybe_generate_key
2016-04-17T03:42:05+0000 [Controller   2016]   File "/home/vagrant/.anyenv/envs/pyenv/versions/2.7.10/lib/python2.7/site-packages/crossbar/controller/node.py", line 52, in <module>
2016-04-17T03:42:05+0000 [Controller   2016]     from crossbar.worker.router import RouterRealm
2016-04-17T03:42:05+0000 [Controller   2016]   File "/home/vagrant/.anyenv/envs/pyenv/versions/2.7.10/lib/python2.7/site-packages/crossbar/worker/router.py", line 63, in <module>
2016-04-17T03:42:05+0000 [Controller   2016]     from crossbar.worker.testee import WebSocketTesteeServerFactory, \
2016-04-17T03:42:05+0000 [Controller   2016]   File "/home/vagrant/.anyenv/envs/pyenv/versions/2.7.10/lib/python2.7/site-packages/crossbar/worker/testee.py", line 44, in <module>
2016-04-17T03:42:05+0000 [Controller   2016]     from crossbar.worker.worker import NativeWorkerSession
2016-04-17T03:42:05+0000 [Controller   2016]   File "/home/vagrant/.anyenv/envs/pyenv/versions/2.7.10/lib/python2.7/site-packages/crossbar/worker/worker.py", line 48, in <module>
2016-04-17T03:42:05+0000 [Controller   2016]     from crossbar.common.process import NativeProcessSession
2016-04-17T03:42:05+0000 [Controller   2016]   File "/home/vagrant/.anyenv/envs/pyenv/versions/2.7.10/lib/python2.7/site-packages/crossbar/common/process.py", line 67, in <module>
2016-04-17T03:42:05+0000 [Controller   2016]     from crossbar.common import checkconfig
2016-04-17T03:42:05+0000 [Controller   2016]   File "/home/vagrant/.anyenv/envs/pyenv/versions/2.7.10/lib/python2.7/site-packages/crossbar/common/checkconfig.py", line 44, in <module>
2016-04-17T03:42:05+0000 [Controller   2016]     from autobahn.websocket.protocol import parseWsUrl
2016-04-17T03:42:05+0000 [Controller   2016] ImportError: cannot import name parseWsUrl
```

**Comment by hdknr** [comment]
``` bash
$ pip uninstall autobahn  -y
$ pip uninstall crossbar -y
$ pip install -e git://github.com/crossbario/autobahn-python.git#egg=autobahn-python
$ pip install -e git://github.com/crossbario/crossbar.git#egg=crossbar  
```
